#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = image_decode_io1_dm365_config
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv6.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xdc.tci:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xdc.tci
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/package.xs.xdt
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/global/Trace.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/global/Trace.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/ITargetFilter.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/io/package.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/io/package.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/PackageContents.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/PackageContents.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/dmai_2_20_00_15/packages/config.bld:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/dmai_2_20_00_15/packages/config.bld
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/ITarget.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/ITarget.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/_gen.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/_gen.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Utils.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Utils.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/package.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/package.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/MVArm9.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/MVArm9.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/Mingw.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/Mingw.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Executable.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Executable.xs
package.mak: config.bld
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/UCArm9.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/UCArm9.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Library.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Library.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_code.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_code.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/ITarget.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/ITarget.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Script.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Script.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/package.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/package.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/arm/GCArmv7A.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/package.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/package.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/IPackage.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/IPackage.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Repository.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/Repository.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/Linux86.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/Linux86.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/bld/BuildEnvironment.xs
package.mak: package.bld
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_data.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/ti/targets/MSP430_large_data.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/io/File.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/io/File.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/global/Clock.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/services/global/Clock.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/template.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/template.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xmlgen2.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xmlgen2.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/include/utils.tci:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/include/utils.tci
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/ITarget.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/ITarget.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/om2.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/om2.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xmlgen.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/xmlgen.xs
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/xdc/tools/configuro/template/compiler.opt.xdt
/home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/package.xs:
package.mak: /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/package.xs
endif

gnu.targets.arm.GCArmv5T.rootDir ?= /opt/arm-2009q1-203//
gnu.targets.arm.packageBase ?= /home/qxd/dm365/dvsdk_dm365_4_02_00_06/xdctools_3_16_03_36/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.ov5T
.PHONY: all,v5T .dlls,v5T .executables,v5T test,v5T
all,v5T: .executables,v5T
.executables,v5T: .libraries,v5T
.executables,v5T: .dlls,v5T
.dlls,v5T: .libraries,v5T
.libraries,v5T: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,v5T
	@$(ECHO) xdc .executables,v5T
	@$(ECHO) xdc .libraries,v5T
	@$(ECHO) xdc .dlls,v5T


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_image_decode_io1_dm365_config.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package image_decode_io1_dm365_config" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,v5T .executables: image_decode_io1_dm365.xv5T

-include package/cfg/image_decode_io1_dm365_xv5T.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/image_decode_io1_dm365_xv5T.dep
endif
package/cfg/image_decode_io1_dm365_xv5T.ov5T : | package/cfg/image_decode_io1_dm365_xv5T.xdl
image_decode_io1_dm365.xv5T:
	$(RM) $@
	@$(MSG) lnkv5T $@ ...
	$(gnu.targets.arm.GCArmv5T.rootDir)/bin/arm-none-linux-gnueabi-gcc    -o $@ package/cfg/image_decode_io1_dm365_xv5T.ov5T  package/cfg/image_decode_io1_dm365_xv5T.xdl  -lstdc++ -L$(gnu.targets.arm.GCArmv5T.rootDir)/arm-none-linux-gnueabi/lib
	
image_decode_io1_dm365.xv5T:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,v5T))
image_decode_io1_dm365.xv5T package/cfg/image_decode_io1_dm365_xv5T.c: .libraries,v5T
endif

package/cfg/image_decode_io1_dm365_xv5T.c package/cfg/image_decode_io1_dm365_xv5T.h package/cfg/image_decode_io1_dm365_xv5T.xdl: override _PROG_NAME := image_decode_io1_dm365.xv5T
package/cfg/image_decode_io1_dm365_xv5T.c: package/cfg/image_decode_io1_dm365_xv5T.cfg
image_decode_io1_dm365.test test,v5T test: image_decode_io1_dm365.xv5T.test

image_decode_io1_dm365.xv5T.test:: image_decode_io1_dm365.xv5T
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 image_decode_io1_dm365.xv5T.test
else
	@$(MSG) running $<  ...
	$(call EXEC.image_decode_io1_dm365.xv5T, ) 
endif


clean:: clean,v5T
	-$(RM) package/cfg/image_decode_io1_dm365_xv5T.cfg
	-$(RM) package/cfg/image_decode_io1_dm365_xv5T.dep
	-$(RM) package/cfg/image_decode_io1_dm365_xv5T.c
	-$(RM) package/cfg/image_decode_io1_dm365_xv5T.xdc.inc

clean,v5T::
	-$(RM) image_decode_io1_dm365.xv5T
	-$(RM) .tmp,image_decode_io1_dm365.xv5T,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
image_decode_io1_dm365_xv5T.ov5T,copy : package/cfg/image_decode_io1_dm365_xv5T.ov5T
image_decode_io1_dm365_xv5T.sv5T,copy : package/cfg/image_decode_io1_dm365_xv5T.sv5T

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,image_decode_io1_dm365_config
image_decode_io1_dm365_config.tar: package/build.cfg
image_decode_io1_dm365_config.tar: package/package.ext.xml
image_decode_io1_dm365_config.tar: package/package.xdc.inc
image_decode_io1_dm365_config.tar: package/package.bld.xml
image_decode_io1_dm365_config.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/image_decode_io1_dm365_config.tar.dep
endif
package/rel/image_decode_io1_dm365_config/image_decode_io1_dm365_config/package/package.rel.xml:

image_decode_io1_dm365_config.tar: package/rel/image_decode_io1_dm365_config.xdc.inc package/rel/image_decode_io1_dm365_config/image_decode_io1_dm365_config/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/image_decode_io1_dm365_config.xdc.inc,package/rel/image_decode_io1_dm365_config.tar.dep)


release release,image_decode_io1_dm365_config: all image_decode_io1_dm365_config.tar
clean:: .clean
	-$(RM) image_decode_io1_dm365_config.tar
	-$(RM) package/rel/image_decode_io1_dm365_config.xdc.inc
	-$(RM) package/rel/image_decode_io1_dm365_config.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
